apiVersion: v1
kind: Service
metadata:
  name: webapp-service # service name accessed by app
spec:
  selector:
    app: webapp # match the pod labels
  ports:
    - protocol: TCP
      port: 5000 # service port
      targetPort: 5000 # pod port
