apiVersion: v1
kind: Service
metadata:
  name: redis-service # service name accessed by app
spec:
  selector:
    app: redis # match the pod labels
  ports:
    - protocol: TCP
      port: 6379 # service port
      targetPort: 6379 # pod port
